### ISSUE TITLE
As a user, I'd like to see an up-to-date population report

### ISSUE THREAD

**Issue by bzatrok** [ufukozsoy/sem#16]
The user should see a print-out of the following population reports:

- [ ] The population of the world.
- [ ] The population of a continent.
- [ ] The population of a region.
- [ ] The population of a country.
- [ ] The population of a district.
- [ ] The population of a city.

**Comment by bzatrok** [comment]
Create population reports in the following format:

Population Report

For the population reports, the following information is requested:

    The name of the continent/region/country.
    The total population of the continent/region/country.
    The total population of the continent/region/country living in cities (including a %).
    The total population of the continent/region/country not living in cities (including a %).

**Comment by vivasvaan** [comment]
//The name of the continent/region/country.
SELECT name , region , continent  
from country 

//population of the country
select name , population from country

//population of region
select Region, sum(population) as "Polulation" from country 
group by Region

Will create the rest two and send asap.
