### ISSUE TITLE
As a developer, I'd like the code to have adequite unit test code coverage.

### ISSUE THREAD

**Issue by bzatrok** [ufukozsoy/sem#39]
- Create unit tests for core app functionality (sql queries & csv generation)

**Comment by BinsaleemAbdulelah** [comment]
package com.napier.sem.models.unit test;


import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;


class MyTest
{
    @Test
    void unitTest()
    {
        assertEquals(name, North America);
    }

@Test
void unitTest3()
{
    assertEquals(country_name, North America, "Messages are equal");
}

@Test
void unitTest4()
{
    assertEquals(5.0, 5.01, 0.02);
}



@Test
void unitTest7()
{
    assertFalse(country_name[5] == country_name[4]);
}

@Test
void unitTest8()
{
    assertNull(null);
}

@Test
void unitTest9()
{
    assertNotNull("Amirica");
}

@Test
void unitTest10()
{
    assertThrows(NullPointerException.class, this::throwsException);
}

void throwsException() throws NullPointerException
{
    throw new NullPointerException();
}
}
